---
# jenkins
#
# Provision a Jenkins instance.
#
# Parameters:
#   `jenkins_user`: jenkins
#   `jenkins_home`: /var/lib/jenkins
#   `jenkins_user_home`: /home/jenkins
#   `jenkins_debian_pkgs`: List of Jenkins-specific Debian packages to install
#   `jenkins_git_ssh_key` (optional): Private key for accessing GitHub
#   `enable_github_status`: If false, stub out `gcli` to avoid reporting build status to GitHub
#   `github_oauth_token` (optional): OAuth token for the account used to update build status on GitHub

- include: jenkins.yml
- include: gcli.yml
- include: xvfb.yml
- include: browsers.yml
- include: python-pkgs.yml
